[tool.coverage.report]
show_missing = true
fail_under = 100.0
skip_covered = true

[tool.coverage.run]
source = ["sshoot"]

[tool.black]
line-length = 88
target-version = ['py37', 'py38', 'py39', 'py310', 'py311']
include = '\.pyi?$'

[tool.isort]
combine_as_imports = true
force_grid_wrap = 2
force_sort_within_sections = true
from_first = false
include_trailing_comma = true
multi_line_output = 3
order_by_type = false
profile = "black"
use_parentheses = true

[tool.mypy]
install_types = true
non_interactive = true
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
