name: sshoot
version: git
summary: Manage sshuttle VPN sessions
description: |
  Command-line interface to manage multiple sshuttle VPN sessions.

  sshoot allows to define multiple VPN sessions using sshuttle and start/stop
  them as needed.

license: GPL-3.0+
confinement: classic
grade: stable
base: core20

apps:
  sshoot:
    command: bin/sshoot
    environment:
      PATH: $SNAP/bin:$SNAP/usr/bin:/bin:$PATH
      PYTHONPATH: $SNAP/lib/python3.8/site-packages
    completer: sshoot-completion

parts:
  sshoot:
    plugin: python
    source: .
    source-type: git
    stage-packages:
      - libpython3-stdlib
      - libpython3.8-stdlib
      - libpython3.8-minimal
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - python3-venv
      - python3-minimal
      - python3-distutils
      - python3-pkg-resources
      - python3.8-minimal
    python-packages:
      - sshuttle
    prime:
      - bin/sshoot
      - bin/sshuttle
      - pyvenv.cfg
      - lib
      - usr/bin
      - usr/lib

  completion:
    plugin: dump
    source: snap/local
